= Spring Boot application inheriting from the (Mock) Spring Boot BOM using version property override

In this test case, the Spring Boot application Maven POM *inherits* from the (Mock) Spring Boot BOM:

.Inherit from the (Mock) Spring Boot BOM
[source, xml]
----
<parent>
    <groupId>io.spring.maven</groupId>
    <artifactId>spring-boot-bom</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</parent>
----

The Spring Boot application is using Spring Data MongoDB and Spring Data Redis:

.Declared Spring Data MongoDB and Spring Data Redis dependencies (no version required)
[source, xml]
----
<dependencies>
    <dependency>
        <groupId>org.springframework.data</groupId>
        <artifactId>spring-data-mongodb</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.data</groupId>
        <artifactId>spring-data-redis</artifactId>
    </dependency>
</dependencies>
----

The Spring Boot application then tries to override the Spring Data Redis dependency version
using the `spring-data-redis.version` property declared in the (Mock) Spring Data BOM:

.Spring Data Redis dependency version override using property
[source,xml]
----
<properties combine.children="override" combine.self="override">
    <spring-data.redis.version>2.7.0</spring-data.redis.version>
</properties>
----

The resulting Maven POM dependency tree for the Spring Boot application is:

.Maven Dependency Tree
[source,txt]
----
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] --< io.spring.maven:spring-boot-app-bom-inheritance-version-property-override >--
[INFO] Building spring-boot-app-bom-inheritance-version-property-override 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spring-boot-app-bom-inheritance-version-property-override ---
[INFO] io.spring.maven:spring-boot-app-bom-inheritance-version-property-override:jar:1.0.0-SNAPSHOT
[INFO] +- org.springframework.data:spring-data-mongodb:jar:4.0.0-M4:compile
[INFO] |  +- org.springframework:spring-tx:jar:6.0.0-M4:compile
[INFO] |  +- org.springframework:spring-context:jar:6.0.0-M4:compile
[INFO] |  +- org.springframework:spring-beans:jar:6.0.0-M4:compile
[INFO] |  +- org.springframework:spring-core:jar:6.0.0-M4:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:6.0.0-M4:compile
[INFO] |  +- org.springframework:spring-expression:jar:6.0.0-M4:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:3.0.0-M4:compile
[INFO] |  +- org.mongodb:mongodb-driver-core:jar:4.6.0:compile
[INFO] |  |  +- org.mongodb:bson:jar:4.6.0:compile
[INFO] |  |  \- org.mongodb:bson-record-codec:jar:4.6.0:runtime
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO] \- org.springframework.data:spring-data-redis:jar:3.0.0-M4:compile
[INFO]    +- org.springframework.data:spring-data-keyvalue:jar:3.0.0-M4:compile
[INFO]    +- org.springframework:spring-oxm:jar:6.0.0-M4:compile
[INFO]    +- org.springframework:spring-aop:jar:6.0.0-M4:compile
[INFO]    \- org.springframework:spring-context-support:jar:6.0.0-M4:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.647 s
[INFO] Finished at: 2022-05-19T17:21:50-07:00
----

Clearly, this does not work, either!
